name: ci

on:
  push:
    branches: master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      -
        name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        id: build_push
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.GCLOUD_PROJECT_ID }}/authn-proxy:latest
      -
        name: Image digest
        run: echo ${{ steps.build_push.outputs.digest }}

